#if !defined(ARRAYLIST_CFG_H)
#define ARRAYLIST_CFG_H
#include "std_types.h"
#define ARRAYLIST_TRUE 1
#define ARRAYLIST_FALSE 0
#define ARRAYLIST_EQUAL 0
#define ARRAYLIST_GREATER 1
#define ARRAYLIST_LESS -1
#define ARRAYLIST_NONEXISTENT_INDEX -1
typedef void* ARRAYLIST_ELEMENT_DATATYPE;
typedef int32 ARRAYLIST_LENGTH_DATATYPE;
typedef ARRAYLIST_LENGTH_DATATYPE ARRAYLIST_INDEX_DATATYPE;
typedef void (*ARRAYLIST_FREE_FUNCTION_POINTER_DATATYPE)(ARRAYLIST_ELEMENT_DATATYPE);
typedef int8 (ARRAYLIST_PREDICATE_FUNCTION)(ARRAYLIST_ELEMENT_DATATYPE);
typedef int8 (*ARRAYLIST_COMPARATOR_FUNCTION)(ARRAYLIST_ELEMENT_DATATYPE, ARRAYLIST_ELEMENT_DATATYPE);
#endif // ARRAYLIST_CFG_H
